# Generated by Django 5.0.4 on 2024-04-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Localizacao', models.CharField(max_length=50)),
                ('Opcao', models.CharField(max_length=50)),
                ('Descricao', models.CharField(max_length=250)),
                ('Foto', models.ImageField(default=None, null=True, upload_to='Fotos_denuncia/')),
            ],
        ),
    ]
