# Generated by Django 5.0.4 on 2024-05-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_pi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariodenuncia',
            name='Latitude',
            field=models.FloatField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='formulariodenuncia',
            name='Longitude',
            field=models.FloatField(default=None, max_length=250),
        ),
    ]
