# Generated by Django 5.0.4 on 2024-04-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_pi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariodenuncia',
            name='Foto',
            field=models.ImageField(default=None, unique=True, upload_to='Fotos_denuncia/'),
        ),
    ]
