# Generated by Django 5.0.4 on 2024-05-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_pi', '0002_alter_formulariodenuncia_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariodenuncia',
            name='Latitude',
            field=models.FloatField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='formulariodenuncia',
            name='Longitude',
            field=models.FloatField(default=None, max_length=250, null=True),
        ),
    ]
