# Generated by Django 5.0.4 on 2024-05-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_pi', '0003_alter_formulariodenuncia_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariodenuncia',
            name='Foto',
            field=models.ImageField(default=None, upload_to='Fotos_denuncia/'),
        ),
    ]
